version: '3'

services:
    wallet-service-api:
        image: wallet-service-docker:latest
        container_name: wallet-service
        hostname: wallet-service
        mem_limit: 512m
        network_mode: bridge
        expose:
            - "8080"
        ports:
            - "8080:8080"
        environment:
            SERVER_PORT: 8080
#       Persistance for H2 DB and Ehcache
        volumes:
            - ./tmp:/tmp
        command: sh -c 'apt-get update && apt-get -qq -y install curl && java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap $$APPLICATION_ARGS -jar /opt/app.jar'
